# Generated by Django 5.2.18 on 2026-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount_paise', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('bills', 'Bills'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('health', 'Health'), ('other', 'Other')], db_index=True, max_length=20)),
                ('spent_on', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-spent_on', '-id'],
            },
        ),
    ]
